import type { NextPageWithLayout } from './_app'
import type { NextPage } from 'next';
import { ReactElement } from 'react'
import Head from 'next/head'
import React from 'react';
import test from "./test.md"
import ReactMarkdown from 'react-markdown'
import Layout from '../components/Layout'


interface Props {
    postTitle: string,
    date: string,
    text: string
}

const Post: NextPage<Props> = ({ postTitle = "No Title", date = "", text = "" }) => {
    return (
        <>
            <h1>{postTitle}</h1>
            <div>{date}</div>
            <ReactMarkdown>{text}</ReactMarkdown>
        </>
    )
}

const Blog: NextPageWithLayout = () => {
    return (
        <>
            <Head>
                <title>Blog</title>
                <meta name="Blog" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="h-full w-screen bg-orange-50 text-stone-800 dark:bg-body-blue dark:text-white">
                <h1 className="pt-16">Blog</h1>
                <Post postTitle={'Lorem Ipsum'} date={'01.01.01'} text={test} />
            </div>
        </>
    )
}

Blog.getLayout = function getLayout(page: ReactElement) {
    return (
      <Layout>
        {page}
      </Layout>
    )
  }

export default Blog