import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react';
import { useState, useEffect } from 'react';

interface Props {
    postTitle: string,
    date: string,
    text: string
}

const Post: NextPage<Props> = ({ postTitle = "No Title", date = "", text = "" }) => {
    return (
        <>
            <h1>{postTitle}</h1>
            <div>{date}</div>
            <div>{text}</div>
        </>
    )
}

const Blog: NextPage = () => {
    return (
        <>
            <Head>
                <title>Blog</title>
                <meta name="Blog" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>Blog</h1>
            <Post postTitle={'Lorem Ipsum'} date={'01.01.01'} text={"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."} />
        </>
    )
}

export default Blog