import { useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import sun from '../images/sun.svg'
import sunw from '../images/sun-w.svg'

const Home: NextPage = () => {
  
  const [darkMode, setDarkMode] = useState(false);

  function swichColorMode() {
    setDarkMode(!darkMode);
    darkMode ? document.body.classList.add("bg-black") : document.body.classList.remove("bg-black")
  }
  
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex justify-end text-red-500 mr-11">
        this is a header
        <Link href="/blog">Posts</Link>
      </header>
        <h1 className="flex justify-center text-red-800 font-extrabold">
          Welcome to my page
        </h1>
        <button onClick={swichColorMode}
        className="ml-11">
        <Image 
        src={sun}
        alt="switch light and dark mode"
        />
        </button>
    </>
  )
}

export default Home
