import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from './layout'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen bg-orange-100 dark:bg-sky-800 dark:text-white">
        <Layout></Layout>
        <h1 className="flex justify-center font-extrabold text-2xl">
          Welcome to my page
        </h1>
        <a
          href="/file.pdf"
          alt="download pdf"
          target="_blank"
          rel="noopener noreferrer"
        >Download File</a>
      </div>
    </>
  )
}

export default Home
